name: google-oauth2-easy
version: '0.0.0'
github: jxv/google-oauth2-easy
license: BSD3
license-file: LICENSE.md
author: Joe Vargas
maintainer: Joe Vargas
synopsis: Opininated use of Google Authentication for ease
description: Easy Google Authentication integration using the Authorization Code Grant and Refresh Token
category: Network

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base >=4.7 && <5
  - aeson
  - unordered-containers
  - http-api-data
  - http-client
  - mtl
  - servant
  - servant-client
  - text
  - text-conversions
  source-dirs: library

benchmarks:
  google-oauth2-easy-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - google-oauth2-easy
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  google-oauth2-easy-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - google-oauth2-easy
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
